set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdtree'

call vundle#end()

filetype plugin indent on

syntax on

set number
set mouse=a

set autoindent
set smartindent

set tabstop=4
set shiftwidth=4
set expandtab

set noesckeys

set incsearch

cnoremap <expr> %% getcmdtype() == ':' ? expand('%:h').'/' : '%%'

